name: Deploy FastAPI Backend to Azure Web App

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Deploy source code to Azure App Service
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'artha-api-live'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE }}
          package: .